name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hdf5
  - netcdf4
  - numpy<2.0
  - pandas<2.0
  - matplotlib<3.5
  - numba>=0.53
  - bqplot
  - platypus-opt
  - pip
